"""
Django settings for voting project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^26h0n!$v*q54mx*=-x6bic%a!8jo4i8!-w-tebi5fzjsef2g4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_middleware_global_request',
    'freedom',
<<<<<<< HEAD
<<<<<<< HEAD
    'django_bootstrap5',
    # 'bootstrap4',
=======
    'bootstrap5',
>>>>>>> 3409599e8033f19433aae308b612cf1988cd5850
=======
    'bootstrap5',
>>>>>>> 3409599e8033f19433aae308b612cf1988cd5850
    'channels',
    
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_middleware_global_request.middleware.GlobalRequestMiddleware',
    
    

]

ROOT_URLCONF = 'voting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'voting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

DATABASE_ROUTERS = [
     
]


DATABASES ={
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Use any valid engine for the default
        'NAME': BASE_DIR / "db.sqlite3",
    },
}
'''  
    'one': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test1_ztah',
        'USER': 'test1_ztah_user',
        'HOST': 'dpg-cmp3hvect0pc73evk7m0-a.oregon-postgres.render.com',
        'PASSWORD': 'Otw8TRzr6M5JhwV39wZAheuCD04BBI3F',
        'PORT': '5432',
    },

    'two': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'test2_ngl2',
            'USER': 'test2_ngl2_user',
            'HOST': 'dpg-cmp3ogect0pc73evlvvg-a.oregon-postgres.render.com',
            'PASSWORD': 'XwRx5T0nCnd0Vy7eOIaTRVbMfIGDfPog',
            'PORT': '5432',
        },

    'three': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'mrt',
            'USER': 'mrt_user',
            'HOST': 'dpg-cn0c9u0cmk4c73am9ohg-a.oregon-postgres.render.com',
            'PASSWORD': 'sKNmfGdx0Ai9n3COgHpPD46UBWU3WDOH',
            'PORT': '5432',
        },

    'four': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'muhumuza',
            'USER': 'muhumuza_user',
            'HOST': 'dpg-cn0esngl5elc73ej93ag-a.oregon-postgres.render.com',
            'PASSWORD': 'EQlf8AGCsVkKgKuTHj0JYaSm2KECFeDO',
            'PORT': '5432',
        },
'''



# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'    

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Additional locations of static files
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
