# Generated by Django 5.0.1 on 2024-01-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village', models.CharField(max_length=30)),
                ('parish', models.CharField(max_length=30)),
                ('sub_county', models.CharField(max_length=30)),
                ('county', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_text', models.CharField(max_length=50)),
                ('luganda_text', models.CharField(max_length=50)),
                ('kiswahili_text', models.CharField(max_length=50)),
                ('english_audio', models.FileField(upload_to='english_audio/')),
                ('luganda_audio', models.FileField(upload_to='luganda_audio/')),
                ('kiswahili_audio', models.FileField(upload_to='kiswahili_audio/')),
                ('cast_voice', models.FileField(upload_to='cast_audio/')),
            ],
        ),
        migrations.CreateModel(
            name='Political_party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('emblem', models.ImageField(upload_to='emblem_images/')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Voter_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('priveledges', models.CharField(choices=[('FP', 'Fingerprint_patterns'), ('VC', 'Voice'), ('BR', 'Braille_keypad')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidate_images/')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=50)),
                ('political_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.political_party')),
            ],
        ),
        migrations.CreateModel(
            name='Polling_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.address')),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('nin_number', models.CharField(max_length=15)),
                ('phone_contact', models.CharField(max_length=10)),
                ('Polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.polling_station')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.address')),
                ('Voter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.voter_type')),
            ],
        ),
        migrations.CreateModel(
            name='Fingerprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_thumb', models.BinaryField()),
                ('right_index_finger', models.BinaryField()),
                ('right_middle_finger', models.BinaryField()),
                ('right_ring_finger', models.BinaryField()),
                ('right_pinky_finger', models.BinaryField()),
                ('left_thumb', models.BinaryField()),
                ('left_index_finger', models.BinaryField()),
                ('left_middle_finger', models.BinaryField()),
                ('left_ring_finger', models.BinaryField()),
                ('left_pinky_finger', models.BinaryField()),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.voter')),
            ],
        ),
    ]
