# Generated by Django 4.2.9 on 2024-05-22 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=100)),
                ('parish', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '1. Addresses',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('political_party', models.CharField(choices=[('NRM', 'NRM'), ('FDC', 'FDC'), ('NUP', 'NUP')], max_length=100)),
                ('post_aspired_for', models.CharField(choices=[('President', 'President'), ('Member of Parliament', 'Member of Parliament'), ('Chairperson LCV', 'Chairperson LCV')], max_length=100)),
            ],
            options={
                'verbose_name_plural': '7. Candidates',
            },
        ),
        migrations.CreateModel(
            name='Polling_Station',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.address')),
            ],
            options={
                'verbose_name_plural': '2. PollingStations',
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('date_of_birth', models.DateField()),
                ('nin_number', models.CharField(max_length=100)),
                ('phone_contact', models.CharField(max_length=100)),
                ('voter_type', models.CharField(choices=[('Blind', 'Blind'), ('Blind_and_Mute', 'Blind_and_Mute'), ('Blind_and_Lame', 'Blind_and_Lame')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('fingerprint_xtics', models.TextField(blank=True, null=True)),
                ('Polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.polling_station')),
            ],
            options={
                'verbose_name_plural': '3. Voters',
            },
        ),
        migrations.CreateModel(
            name='FingerPrints',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hand', models.CharField(choices=[('Right_Hand', 'Right_Hand'), ('Left_Hand', 'Left_Hand')], max_length=10)),
                ('finger', models.CharField(choices=[('Thumb', 'Thumb'), ('Index Finger', 'Index Finger'), ('Middle Finger', 'Middle Finger'), ('Ring Finger', 'Ring Finger'), ('Pinky Finger', 'Pinky Finger')], max_length=13)),
                ('fingerprint_image', models.BinaryField(default=b'')),
                ('voter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freedom.voters')),
            ],
            options={
                'verbose_name_plural': '4. FingerPrints',
            },
        ),
        migrations.CreateModel(
            name='CastedVotes',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.candidates')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.voters')),
            ],
            options={
                'verbose_name_plural': '8. CastedVotes',
            },
        ),
    ]
