# Generated by Django 4.2.9 on 2024-05-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0002_alter_candidates_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
