# Generated by Django 4.2.9 on 2024-02-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0003_alter_fingerprints_left_index_finger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
