# Generated by Django 4.2.9 on 2024-05-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0003_alter_candidates_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
