# Generated by Django 4.2.9 on 2024-02-09 15:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0007_fingerprintbinarydata_voter_alter_candidate_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audios',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_text', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='Audios')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '6. Audios',
            },
        ),
        migrations.CreateModel(
            name='AudioTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_type', models.CharField(choices=[('English', 'English'), ('Luganda', 'Luganda'), ('Kiswahili', 'Kiswahili')], max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '5. AudioTypes',
            },
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_pic', models.ImageField(upload_to='Candidates')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('political_party', models.CharField(choices=[('NRM', 'NRM'), ('FDC', 'FDC'), ('NUP', 'NUP')], max_length=100)),
                ('post_aspired_for', models.CharField(choices=[('Post-1', 'Post-1'), ('Post-2', 'Post-2'), ('Post-3', 'Post-3'), ('Post-4', 'Post-3')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '7. Candidates',
            },
        ),
        migrations.CreateModel(
            name='CastedVotes',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.candidates')),
            ],
            options={
                'verbose_name_plural': '8. CastedVotes',
            },
        ),
        migrations.CreateModel(
            name='FingerPrints',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hand', models.CharField(choices=[('Right_Hand', 'Right_Hand'), ('Left_Hand', 'Left_Hand')], max_length=100)),
                ('finger', models.CharField(choices=[('Thumb', 'Thumb'), ('Index Finger', 'Index Finger'), ('Middle Finger', 'Middle Finger'), ('Ring Finger', 'Ring Finger'), ('Pinky Finger', 'Pinky Finger')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '4. FingerPrints',
            },
        ),
        migrations.CreateModel(
            name='PollingStation',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '2. PollingStations',
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('date_of_birth', models.DateField()),
                ('nin_number', models.CharField(max_length=100)),
                ('phone_contact', models.CharField(max_length=100)),
                ('voter_type', models.CharField(choices=[('Blind', 'Blind'), ('Blind_and_Mute', 'Blind_and_Mute'), ('Blind_and_Lame', 'Blind_and_Lame')], max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('Polling_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.pollingstation')),
            ],
            options={
                'verbose_name_plural': '3. Voters',
            },
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.RemoveField(
            model_name='fingerprintbinarydata',
            name='voter',
        ),
        migrations.RemoveField(
            model_name='polling_station',
            name='address',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='Polling_station',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='Voter_type',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='address',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': '1. Addresses'},
        ),
        migrations.AddField(
            model_name='address',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 2, 9, 15, 26, 4, 525677, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='parish',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='sub_county',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='village',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='FingerprintBinaryData',
        ),
        migrations.DeleteModel(
            name='Political_party',
        ),
        migrations.DeleteModel(
            name='Polling_station',
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
        migrations.DeleteModel(
            name='Voter_type',
        ),
        migrations.AddField(
            model_name='pollingstation',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.address'),
        ),
        migrations.AddField(
            model_name='fingerprints',
            name='voter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='freedom.voters'),
        ),
        migrations.AddField(
            model_name='castedvotes',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.voters'),
        ),
        migrations.AddField(
            model_name='audios',
            name='audio_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freedom.audiotypes'),
        ),
    ]
