# Generated by Django 4.2.9 on 2024-02-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0011_alter_audiotypes_audio_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='post_aspired_for',
            field=models.CharField(choices=[('President', 'President'), ('Member of Parliament', 'Member of Parliament'), ('Chairperson LCV', 'Chairperson LCV')], max_length=100),
        ),
    ]
