# Generated by Django 4.2.11 on 2024-04-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0013_fingerprints_fingerprint_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='voters',
            name='fingerprint_xtics',
            field=models.TextField(blank=True, null=True),
        ),
    ]
