# Generated by Django 5.0.4 on 2024-04-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freedom', '0015_alter_voters_managers_voters_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='voters',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='voters',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='email',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='password',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='voters',
            name='username',
        ),
    ]
